version: '3.8'

services:
  golang-backend:
    image: golang:latest
    container_name: golang-backend
    volumes:
      - ./chatbot-backend:/app
    working_dir: /app
    command: make run-ci
    ports:
      - "8080:8080"

  python-backend:
    build:
      context: ./chatbot-backend/audiocraft
      dockerfile: Dockerfile
    container_name: python-backend
    volumes:
      - ./chatbot-backend/audiocraft:/app
    ports:
      - "5001:5000"

  frontend:
    image: node:14
    container_name: frontend
    volumes:
      - ./chatbot-frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run start"
    ports:
      - "3000:3000"
